
server:
  port: 8080
spring:
  task:
    scheduling:
      pool:
        size: 10
  mvc:
    servlet:
      path: /api
  jackson:
    mapper:
      accept-case-insensitive-properties: true
  datasource:
    url: ${db.url:jdbc:postgresql://localhost:5432/postgres}
    username: ${db.username:postgres}
    password: ${db.password:_PLKbnty15LOH}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 60000
      maximum-pool-size: 50
logging:
  file:
    max-history: 20

hash.key: 1ydvas5